site_name: /DevBlog > Siddharth Chillale
site_description: A Memoir of the Adventures in Code
site_author: Siddharth Chillale
nav:
    - 'Home': 'index.md'
    - 'Personal Projects': 'projects.md'
    - "Bucket List": "Things_I_Plan_to_do.md"
    - "Blog":
        - 'Dev logs':
                - "Project: Corona": "Corona.md"
        - "Gain experience": "What to do to gain experience.md"
        - "LinkedIn Tips" : "LinkedIn_tips.md"
        - "Git mistakes": "Git_Mistakes.md"
        


theme:
    name: material

extra_css: 
    - css/extra.css


markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.smartsymbols
    - pymdownx.mark
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.betterem:
        smart_enable: 'underscore'
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - footnotes
    - meta
    - pymdownx.tasklist:
        custom_checkbox: true



repo_url: https://github.com/SiddharthChillale/devblog

repo_name: /devblog